version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodapp
    ports: ["5432:5432"]
  auth-service:
    build: ./auth-service
    environment:
      PG_JDBC: jdbc:postgresql://postgres:5432/foodapp
      PG_USER: postgres
      PG_PASSWORD: postgres
      JWT_SECRET: change_me_ultra_secret
    depends_on: [postgres]
    ports: ["8081:8081"]
  user-service:
    build: ./user-service
    environment:
      PG_JDBC: jdbc:postgresql://postgres:5432/foodapp
      PG_USER: postgres
      PG_PASSWORD: postgres
      JWT_SECRET: change_me_ultra_secret
    depends_on: [postgres]
    ports: ["8082:8082"]
  gateway:
    build: ./gateway
    environment:
      JWT_SECRET: change_me_ultra_secret
    depends_on: [auth-service, user-service]
    ports: ["8080:8080"]
