server:
  port: 8082
spring:
  datasource:
    url: ${PG_JDBC:jdbc:postgresql://postgres:5432/foodapp}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: core
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: core
    default-schema: core

security:
  jwt:
    secret: ${JWT_SECRET:change_me_ultra_secret}
