name: Deploy Gateway

on:
  push:
    paths:
      - "gateway/**"
      - ".github/workflows/gateway.yml"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Gateway JAR
        run: mvn -pl gateway clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jshashank388/foodappgateway:latest ./gateway

      - name: Push Docker image
        run: docker push jshashank388/foodappgateway:latest

      - name: Deploy to Railway
        run: railway up --service gateway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
