name: Deploy Auth Service

on:
  push:
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-service.yml"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Auth Service JAR
        run: mvn -pl auth-service clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jshashank388/foodappauthservice:latest ./auth-service

      - name: Push Docker image
        run: docker push jshashank388/foodappauthservice:latest

      - name: Deploy to Railway
        run: railway up --service auth-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
