name: Deploy Auth Service

on:
  push:
    paths:
      - 'common-libs/**'
      - 'user-service/**'
      - '.github/workflows/user-service.yml'
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR (common-libs + user-service)
        run: mvn -pl common-libs,user-service -am clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jshashank388/foodappuserservice:latest -f user-service/Dockerfile .

      - name: Push Docker image
        run: docker push jshashank388/foodappuserservice:latest

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway up --service foodappuserservice --detach

#          railway up --detach --service foodappuserservice
